name: Setup Ruby Environment
description: Reusable steps for setting up Ruby
runs:
  using: "composite"
  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version-file: .tool-versions
        bundler-cache: true
